### ISSUE TITLE
hw95

### ISSUE THREAD

**Issue by amelendez19** [dtmak1/BlackDogs#3]
**Statement of the problem**
We would stick with the first one. We see how you try to account for the recursive abstraction with the second one, but we don't think it matters for the statement of the problem.

**Recursive Abstraction**
This is sort of nitpicky, but based on the statement of the problem, you (and the recursive abstraction) are not asked to find a solution, rather you are asked to find whether or not there is a solution.

**Base case**
This is the least important of the comments, but you might consider the fact that it is not the action of moving onto the treasure that is the base case. It's the calling of the recursive abstraction while the explorer is already on the treasure.

**Algorithm**
This is a small but pivotal part of the algorithm: You need something to prevent looping.

**Comment by shinbamba** [comment]
Thank you for your constructive comments on our algorithm. We appreciate you helping us improve our code.
